'use strict';

const FILTERS = [
  { key: 'instances', label: 'Instances', table: 'Instances', field: 'nom_instance', source: 'Instances', color: '#4f8ee8' },
  { key: 'actions', label: 'Actions', table: 'Actions', field: 'Action', source: 'Actions', color: '#f28a54' },
  { key: 'gt', label: 'GT', table: 'GT', field: 'nom', source: 'GT', color: '#1ba99a' },
  { key: 'taches', label: 'Tâches', table: 'Taches', field: 'taches', source: 'Taches', color: '#d79a25' },
  { key: 'competences', label: 'Compétences', table: 'Competances', field: 'Competences', source: 'Competances', color: '#6257d9' },
  { key: 'communautes', label: 'Communautés', table: 'Communautees', field: 'communaute', source: 'Communautees', color: '#d85b9d' }
];
const TAG_GROUPS = FILTERS.concat([{ key: 'etablissement', label: 'Établissement', color: '#147c72' }, { key: 'role', label: 'Rôle PUI', color: '#8b5fc4' }]);
const activeFilters = Object.fromEntries(FILTERS.map(f => [f.key, new Set()]));
const refMaps = {};
let contacts = [], searchTerm = '', referencesPromise = null;

console.log('[INIT] Démarrage du widget Annuaire PUI');
grist.ready({ requiredAccess: 'read table' });
console.log('[GRIST] Accès lecture demandé');
grist.onRecords(async records => {
  console.log('[GRIST] Records reçus:', records.length);
  contacts = records.filter(record => safeValues(record.perimetre_all).length > 0).map(normalizeRecord);
  console.log('[FILTERS] Records conservés avec perimetre_all:', contacts.length);
  await loadReferenceTables();
  render();
});
function safeValues(value) { if (Array.isArray(value)) return value.filter(item => item !== 'L' && item !== null && item !== undefined && item !== 0 && item !== ''); return value === null || value === undefined || value === '' || value === 0 ? [] : [value]; }
function text(value) { return value === null || value === undefined ? '' : String(value).trim(); }
function normalizeRecord(record) { const competences = []; for (let i = 1; i <= 15; i += 1) { const value = text(record['competences_' + i]); if (value) competences.push(value); } return { id: record.id, nom: text(record.Nom), prenom: text(record.Prenom), fonction: text(record.fonction), email: text(record.Email), telephone: text(record.numero_de_telephone), etablissementId: record.Etablissement, etablissementFallback: text(record.Etablissement2), instanceIds: safeValues(record.Instances), actionIds: safeValues(record.Actions), gtIds: safeValues(record.GT), tacheIds: safeValues(record.Taches), communauteIds: safeValues(record.Communautee_s_), competences, roleId: record.Role_dans_le_PUI }; }
async function fetchRef(table, field, aliases = []) { for (const name of [table].concat(aliases)) { try { const data = await grist.docApi.fetchTable(name); const ids = Array.isArray(data.id) ? data.id : []; const labels = data[field] || data.nom || data.name || []; refMaps[table] = {}; ids.forEach((id, i) => { const label = text(labels[i]); if (label) refMaps[table][String(id)] = label; }); console.log('[REFS] ' + table + ': ' + Object.keys(refMaps[table]).length + ' entrées (' + name + ')'); return; } catch (error) { console.warn('[REFS] Échec pour ' + name, error); } } refMaps[table] = {}; }
function loadReferenceTables() { if (!referencesPromise) { console.log('[REFS] Chargement des tables de référence'); referencesPromise = Promise.all(FILTERS.map(f => fetchRef(f.source, f.field, f.source === 'Competances' ? ['Competences'] : []))).then(() => Promise.all([fetchRef('Etablissements', 'nom_complet'), fetchRef('Role_Dans_le_PUI', 'Role')])); } return referencesPromise; }
function lookup(table, id) { return id === null || id === undefined || id === '' ? '' : (refMaps[table] || {})[String(id)] || ''; }
function enrich(c) { return Object.assign({}, c, { instances: c.instanceIds.map(id => lookup('Instances', id)).filter(Boolean), actions: c.actionIds.map(id => lookup('Actions', id)).filter(Boolean), gts: c.gtIds.map(id => lookup('GT', id)).filter(Boolean), taches: c.tacheIds.map(id => lookup('Taches', id)).filter(Boolean), communautes: c.communauteIds.map(id => lookup('Communautees', id)).filter(Boolean), etablissement: lookup('Etablissements', c.etablissementId) || c.etablissementFallback, role: lookup('Role_Dans_le_PUI', c.roleId) }); }
function collectFacets(list) { const facets = Object.fromEntries(FILTERS.map(f => [f.key, new Map()])); list.forEach(c => FILTERS.forEach(f => (c[f.key] || []).forEach(value => facets[f.key].set(value, (facets[f.key].get(value) || 0) + 1)))); console.log('[FILTERS] Facettes:', Object.fromEntries(FILTERS.map(f => [f.key, facets[f.key].size]))); return facets; }
function matches(c) { const term = searchTerm.toLocaleLowerCase('fr-FR'); if (term && ![c.nom, c.prenom].some(v => v.toLocaleLowerCase('fr-FR').includes(term))) return false; return FILTERS.every(f => !activeFilters[f.key].size || (c[f.key] || []).some(v => activeFilters[f.key].has(v))); }
function render() { console.log('[RENDER] Mise à jour des filtres et des cartes'); const enriched = contacts.map(enrich); renderFilters(collectFacets(enriched)); const visible = enriched.filter(matches).sort((a, b) => a.nom.localeCompare(b.nom, 'fr-FR') || a.prenom.localeCompare(b.prenom, 'fr-FR')); renderActiveFilters(); renderCards(visible); document.getElementById('resultCount').textContent = visible.length + ' contact' + (visible.length > 1 ? 's' : ''); document.getElementById('emptyState').hidden = visible.length !== 0; console.log('[CARDS] Cartes affichées:', visible.length); }
function renderFilters(facets) { console.log('[FILTERS] Rendu des 6 catégories'); const container = document.getElementById('filtersContainer'); container.innerHTML = ''; FILTERS.forEach(f => { const wrapper = document.createElement('div'); wrapper.className = 'filter'; const button = document.createElement('button'); button.type = 'button'; button.className = 'filter-button'; button.innerHTML = '<span class="filter-dot"></span><span>' + f.label + '</span><span class="filter-count">' + activeFilters[f.key].size + '</span><span class="chevron">▾</span>'; button.querySelector('.filter-dot').style.backgroundColor = f.color; const menu = document.createElement('div'); menu.className = 'filter-menu'; menu.style.borderTopColor = f.color; [...facets[f.key].entries()].sort((a, b) => a[0].localeCompare(b[0], 'fr-FR')).forEach(([value, count]) => { const option = document.createElement('label'); option.className = 'filter-option'; const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.checked = activeFilters[f.key].has(value); checkbox.addEventListener('change', () => toggleFilter(f.key, value)); const label = document.createElement('span'); label.className = 'option-label'; label.textContent = value; const countEl = document.createElement('span'); countEl.className = 'option-count'; countEl.textContent = count; option.append(checkbox, label, countEl); menu.appendChild(option); }); button.addEventListener('click', event => { event.stopPropagation(); document.querySelectorAll('.filter.open').forEach(item => { if (item !== wrapper) item.classList.remove('open'); }); wrapper.classList.toggle('open'); }); menu.addEventListener('click', event => event.stopPropagation()); wrapper.append(button, menu); container.appendChild(wrapper); }); }
function toggleFilter(key, value) { activeFilters[key].has(value) ? activeFilters[key].delete(value) : activeFilters[key].add(value); render(); }
function renderActiveFilters() { const target = document.getElementById('activeFilters'); target.innerHTML = ''; FILTERS.forEach(f => activeFilters[f.key].forEach(value => { const chip = document.createElement('span'); chip.className = 'active-chip'; chip.textContent = f.label + ' : ' + value; target.appendChild(chip); })); }
function renderCards(list) { const grid = document.getElementById('cardsGrid'); grid.innerHTML = ''; const template = document.getElementById('cardTemplate'); list.forEach(c => { const node = template.content.cloneNode(true); node.querySelector('.avatar').textContent = ((c.prenom[0] || '') + (c.nom[0] || '')).toUpperCase() || '?'; node.querySelector('.name').textContent = (c.prenom + ' ' + c.nom).trim() || 'Sans nom'; setText(node.querySelector('.fonction'), c.fonction); setText(node.querySelector('.structure'), c.etablissement); setText(node.querySelector('.tel'), c.telephone ? '☎ ' + c.telephone : ''); const email = node.querySelector('.email'); if (c.email) { email.textContent = c.email; email.href = 'mailto:' + c.email; email.classList.add('visible'); } const tags = node.querySelector('.card-tags'); TAG_GROUPS.forEach(g => appendTagGroup(tags, g, g.key === 'etablissement' ? (c.etablissement ? [c.etablissement] : []) : g.key === 'role' ? (c.role ? [c.role] : []) : c[g.key] || [])); grid.appendChild(node); }); }
function appendTagGroup(container, group, list) { if (!list.length) return; const section = document.createElement('section'); section.className = 'tag-group'; const title = document.createElement('h3'); title.className = 'tag-group-title'; title.textContent = group.label; title.style.color = group.color; section.appendChild(title); const values = document.createElement('div'); values.className = 'tag-group-values'; list.forEach(value => { const tag = document.createElement('button'); tag.type = 'button'; tag.className = 'tag tag-' + group.key; tag.style.backgroundColor = group.color; tag.textContent = value; if (activeFilters[group.key]) tag.addEventListener('click', () => toggleFilter(group.key, value)); values.appendChild(tag); }); section.appendChild(values); container.appendChild(section); }
function setText(element, value) { if (value) { element.textContent = value; element.classList.add('visible'); } }
document.getElementById('searchInput').addEventListener('input', e => { searchTerm = e.target.value.trim(); render(); });
document.getElementById('resetFilters').addEventListener('click', () => { FILTERS.forEach(f => activeFilters[f.key].clear()); searchTerm = ''; document.getElementById('searchInput').value = ''; render(); });
document.addEventListener('click', () => document.querySelectorAll('.filter.open').forEach(f => f.classList.remove('open')));
console.log('[INIT] ✅ App initialisé, en attente des données Grist');